---
jobs:
- name: (( grab metadata.job.name ))
  serial: true
  public: true
  plan:
    - aggregate:
      - get: geode
        passed: [Build]
        trigger: true
      - get: geode-ci
      - get: geode-build-version
        passed: [Build]
      - get: docker-geode-build-image
        params:
          rootfs: true
    - task: runtests
      image: docker-geode-build-image
      tags: (( grab metadata.job.size ))
      privileged: true
      timeout: (( grab metadata.job.timeout ))
      config:
        inputs:
          - name: geode
          - name: geode-ci
          - name: docker-geode-build-image
          - name: geode-build-version
        platform: linux
        outputs:
          - name: built-geode
        params:
          MAINTENANCE_VERSION: (( grab metadata.geode-build-branch ))
          SERVICE_ACCOUNT: ((!concourse-gcp-account))
          PUBLIC_BUCKET: ((!public-bucket))
          PARALLEL_DUNIT: (( grab metadata.job.dunit.parallel ))
          DUNIT_PARALLEL_FORKS: (( grab metadata.job.dunit.forks ))
          CALL_STACK_TIMEOUT: (( grab metadata.job.call_stack_timeout ))
        run:
          args:
          - (( grab metadata.job.gradle_task ))
          - (( grab metadata.job.artifact_slug ))
          path: geode-ci/ci/scripts/test-run.sh
      on_failure:
        aggregate:
          - put: send-notification-email
            params:
              subject: built-geode/subject
              body: built-geode/body
      ensure:
        aggregate:
        - task: archive-results
          image: docker-geode-build-image
          config:
            inputs:
              - name: geode
              - name: geode-ci
              - name: geode-build-version
              - name: built-geode
            platform: linux
            params:
              MAINTENANCE_VERSION: (( grab metadata.geode-build-branch ))
              SERVICE_ACCOUNT: ((!concourse-gcp-account))
              PUBLIC_BUCKET: ((!public-bucket))
            run:
              args:
              - (( grab metadata.job.gradle_task ))
              - (( grab metadata.job.artifact_slug ))
              path: geode-ci/ci/scripts/test-archive.sh
